### PR TITLE
Django 2.0 version

### PR DESCRIPTION
**Pull request by cyberbudy**
Fixes to work with django >= 2.0 versions and python 3.6

### CODE REVIEW

**Comment by bufke** [comment]
Thanks for the pull request. I want to support all current versions of Django - which at [this time](https://www.djangoproject.com/download/) is just 1.11 and 2.0 

Test this out with tox - you'll have to adjust the tox.ini to be something like 

```
[tox]
toxworkdir={env:TOX_WORK_DIR:.tox}
envlist = py{36}-django{111,20}

[testenv]
passenv = *
install_command = pip install {opts} {packages}
deps =
    django111: django>=1.11,<1.12
    django20: django>=2.0,<2.1
    -r{toxinidir}/requirements.txt
commands =
    {envpython} {toxinidir}/manage.py test --noinput
```

You can run tox locally or from the included dockerfile. The tox.ini change should be included with the pull request too.

Right now it fails both 1.11 and 2.0.

```
  File "/code/report_builder_demo/urls.py", line 1, in <module>
    from django.urls import path, include
ImportError: cannot import name 'path'
```

```
  File "/code/.tox/py36-django20/lib/python3.6/site-packages/django_celery_beat/models.py", line 176, in PeriodicTask
    null=True, blank=True, verbose_name=_('interval'),
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

Once we can support both 1.11 and 2.0 and all tests pass I'll gladly accept!

**Comment by bufke** [comment]
Also for clarity - just due to the timing of this I'll be dropping support for Django 1.8 and 1.10. So don't worry about those. We'll just make it 6.0 and note 1.8 users will need to use 5.x.

**Comment by cyberbudy** [comment]
Ok. 
Great project by the way.

**Comment by bufke** [comment]
Thanks, I'll review at work Monday

**Comment by bufke** [comment]
1.8 is passing now. 2.0 still fails

```
  File "/code/.tox/py36-django20/lib/python3.6/site-packages/django_celery_beat/models.py", line 166, in <module>
    class PeriodicTask(models.Model):
  File "/code/.tox/py36-django20/lib/python3.6/site-packages/django_celery_beat/models.py", line 176, in PeriodicTask
    null=True, blank=True, verbose_name=_('interval'),
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by bufke** [comment]
Ah I tested it incorrectly before. Thanks!
